FROM python:3.8.3-slim-buster

RUN mkdir -p /home/app

# create the "app" user
RUN addgroup --system app && adduser --system --group app 

ENV HOME=/home/app  
ENV APP_HOME=/home/app/web

RUN mkdir $APP_HOME

# Set environments variables

